### ISSUE TITLE
When EKYC Module will be added? If added how to use?

### ISSUE THREAD

**Issue by corientdev** [souvikdc9/aadhaarapi.net#2]
Hi,

Thanks for this amazing library curious to know when ekyc module will be added?

If already added then how to use?

**Comment by corientdev** [comment]
Anybody here to support

**Comment by ghost** [comment]
Currently, we don't have any fixed date to fix the e-KYC error. As the actual reason that is causing the K-999 error is still unclear. Look over to Aadhaar discussion group, you will get huge number of K-999 error issues, specially on .NET platform.

We are planning to fix the error and update the library to newer API version along with publishing a release version of the library, but no date has been fixed still yet.

**Comment by corientdev** [comment]
Ok. And just for your notice. It doesn't work with Web Application because of so many async call which contribute to deadlocks

**Comment by corientdev** [comment]
Pleasse check this link
https://groups.google.com/forum/#!searchin/aadhaarauth/K-999|sort:relevance/aadhaarauth/caN7no_IvuI/P-80HD1XAQAJ

It has a solution:

Dear Sir,
  I added ns2 and xmlns namespace to pid block as follows:

`````` xml
<ns2:Pid ts="2016-09-26T12:28:54" xmlns:ns2="http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0">```

...........


</ns2:Pid>

 and removed the ns2 namespace from Auth and kyc as follows:

<Auth xmlns="http://www.uidai.gov.in/authentication/uid-auth-request/1.0" ac="public" lk="MBFWjkJHNF-fLidl8oOHtUwgL5p1ZjDbWrqsMEVEJLVEDpnlNj_CZTg" sa="public" tid="public" txn="UKC:public:20160926122854630" uid="999988871435" ver="1.6">

................


</Auth>


<Kyc xmlns="http://www.uidai.gov.in/kyc/uid-kyc-request/1.0" de="Y" lr="N" mec="N" ra="F" rc="Y" ts="2016-09-26T12:28:54" ver="1.0">

.......

</Kyc>



Rest everything was ok.`
``````

**Comment by corientdev** [comment]
@souvikdc9  Kindly look into this as we are getting more and more request for this and you are the only hope. Today morning i have received email referencing this project asking me about the progress. That means he also wants the same.

So, +1 on his behalf too.

**Comment by ghost** [comment]
I understand your concern. Try adding the following code in the library.

PersonalInfo.cs.ToXml()

```
XNamespace ns2 = "http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0";
var personalInfo = new XElement(ns2 + elementName,
    new XAttribute("ts", Timestamp.ToString(AadhaarHelper.TimestampFormat,
    CultureInfo.InvariantCulture)), ......);
```

ApiRequest.cs.ToXml()

```
XNamespace ns2 = "http://www.uidai.gov.in/authentication/uid-auth-request/1.0";
XElement request;
if (elementName == "Auth")
    request = new XElement(ns2 + elementName,
        new XAttribute("tid", Terminal),
        new XAttribute("ac", AuaCode),
        new XAttribute("sa", SubAuaCode),
        new XAttribute("txn", Transaction),
        new XAttribute("lk", AuaLicenseKey));
else
    request = new XElement(elementName,
        new XAttribute("tid", Terminal), .........);
```

Adding the code may make the request successful in development mode. However,
1) On adding it, the e-KYC XML data that is received will perhaps throw error, (cannot be parsed).
2) Adding the namespace may not work in production environment.

I'm not currently finding time to fix the issues, however when I do, I will push several changes to library at once.

If you have added the code, and it worked, please let me know.

**Comment by corientdev** [comment]
Unfortunately i cannot test it as my aadhar number is not added in UIDAI staging database which is required in case of e-Kyc. Same is the case with other guy also. So, we are fully dependent on you now.

Only question i have currently is when can i expect your next push to this wonderful library.

**Comment by yogeshtk77** [comment]
any good news with fix ?

**Comment by corientdev** [comment]
@souvikdc9  can you please share your contact details?

**Comment by yogeshtk77** [comment]
Hello,
My contact details are in below in my email signature. Thanks for your time. You may contact at your convenient time or share your contact details.



Thanks and Regards,
Yogesh Khandge, PMP

Mastek Ltd | B1, 2nd Floor, Cerebrum IT Park,
Kalyani Nagar, Pune 411 014, India, (T) 91 20 27032015
Extn - 6002,  www.mastek.com<http://www.mastek.com/>
Mob:- 8888 912344

Reduce .. Reuse … Recylce ---> I am talking about Code ☺

**Comment by ghost** [comment]
e-KYC fixed.

**Comment by corientdev** [comment]
You are awesome.. appreciate it bro.. a lotOn Apr 24, 2017 1:05 PM, Souvik Dey Chowdhury <notifications@github.com> wrote:e-KYC fixed.

**Comment by Pavankumar12** [comment]
Hi Guys,

Can any one implemented ekyc project in their web application, iam doing but iam not able do,please suggest me the steps how can proceed.

Thanks and Regards
Pavankumar

**Comment by ghost** [comment]
What error are you getting in the web app? Please explain in detail.

Regards,
Souvik DC
