### ISSUE TITLE
Error 501 while using production certificate

### ISSUE THREAD

**Issue by hgehlot07** [souvikdc9/aadhaarapi.net#4]
Hi Team

I am using AUA.p12 downloaded from github and uidai_auth_prod.cer from Aadhaar site. i have implemented Nuget Aadhaar Package. while executing with uidai_auth_stag.cer it is working fine. But while using procuction certificate it is giving Error "501" CI value can not be hardcoded. Please help i am stucked for long no help anywhere. I will be thankful if you could reply to my mail.
Thanking you

Code is below:

                var signerAndVerifier = new XmlSignature
                {
                    Signer = new X509Certificate2(configuration.AuaSignatureKeyPath, "public", X509KeyStorageFlags.Exportable),
                    Verifier = new X509Certificate2(configuration.UidaiSignatureKeyPath)
                };

                using (var sessionKey = new SessionKey(Configuration.UidaiEncryptionKeyPath, false))
                    await deviceContext.EncryptAsync(personalInfo, sessionKey);
var apiClient = new AuthClient
            {
                AgencyInfo = Configuration.AgencyInfo,
                Request = new AuthRequest(deviceContext) { Signer = Signer },
                Response = new AuthResponse { Verifier = Verifier }

            };

    await apiClient.GetResponseAsync();

h.gehlot07@gmail.com

**Comment by ghost** [comment]
Try following the steps, and check if the issue still persists.

1. Firstly, test it with PreProduction keys, available on the UIDAI Developer website.

2. If not solved, recheck if you are using the correct UIDAI encryption key. Encryption key and signature key are different in production environment.

3. Try viewing the final XML in debug mode and manually compare the generated ci value with expiry date of the UIDAI encryption key, the ci identifier should be in the "YYYYMMDD" format.

4. If the problem still persists, contact Aadhaar technical team.

**Comment by hgehlot07** [comment]
Hi Souvik

First of all, Thanks for the reply.  See the code for Auth has this region known as Device to Agency and it was commented, shown below:
  #region Device to Agency
            // TODO: Wrap DeviceContext{T} into AUA specific protocol and send it to AUA.
            // On Device Side:
//             var deviceXml = deviceContext.ToXml();
          //   var wrapped = WrapIntoAuaProtocol(deviceXml);

            // On Agency Side:
            // var auaXml = UnwrapFromAuaProtocol(wrapped);
   //          var auaContext = new AuthContext();
            // auaContext.FromXml(auaXml);
            #endregion

I just uncommented deviceXml and found the xml going as device context as follows:

{<Auth uid="757759114195" tid="public" ts="2017-01-11T16:00:46" info="02{5985A44FE0C89A3A281A77B012527FFB384F08384073C34F21DF9399E108685E,EF58BD753FA309138ACD25466F23BFE08FE5B5E36EF7F77CBB3AEA12EC2609AF,,,20170111160046,,,,,,,,,,,,,,,,,,,,EFA1F375D76194FA51A3556A97E641E61685F914D446979DA50A551A4333FFD7}">
  <Meta udc="ABCDE.20150101.00001" fdc="NA" idc="NA" pip="NA" lot="G" lov="21,78,0" />
  <Skey ci="20170227">NbMR6W7u/9bukL5/6LLnGypU2O2CtUamqjVrQc92gP110CvDI+3vCwki+4GB5fl0N0z3YipYAR91hEo4CCqS3nHXhEQhV+UC9pH1Tq9TiUQHB+5uC6fI4EJgAS0ZCrAP2XqGYwhtHdM+ANkI5NdL6LFJZKwVhN8GMnLxfbphHFldtQJSJ94znR4vYepncPVerVdF4sNFW5s4sJ9xFfgQcD6UTM8OgadhHI7YnmEnB4FYwN628KSML4cmFBFux0Hs9wlmI5Hova1bXuvh12FDgIs0qTdAkT7a0O3y9XXJAfyi883WnIBJDAJg7haZhVfD4rqWzSOVxXx1o6iOtac66Q==</Skey>
  <Data type="X">Uofe+M5yhH+CRNteaFGFEZd4nnfDXxOfT3yiH9XdBulTJ74beiSFjAIRHS/sYKe/Ia/qFEtLj0tMSxQFkggYplk8Ju9BQQ+Mlq0aQKOejZI=</Data>
  <Hmac>3eP5wfunA5n0olDnZXNZYP4mmK4Nyq/+k54zUK2lboSeg6ku0kCj7KqUOnSaOCiM</Hmac>
  <Uses pi="y" pa="n" pfa="n" bio="n" otp="n" pin="n" />
</Auth>}

Now there are few questions as 👍 
1. why this code was commented .
2. when we try to uncomment and run it , it is unableto wrapauprotocol and then unwrap.

And still showing the same 501 error even after trying the latest production certificate and aua.p12 signature available at adhaar site.

Please help/guide. I will be thankful.

Thanking you
Himanshu Gehlot
h.gehlot07@gmail.com

**Comment by hgehlot07** [comment]
XML


{<Auth uid="757759114195" tid="public" ts="2017-01-11T16:00:46" info="02{5985A44FE0C89A3A281A77B012527FFB384F08384073C34F21DF9399E108685E,EF58BD753FA309138ACD25466F23BFE08FE5B5E36EF7F77CBB3AEA12EC2609AF,,,20170111160046,,,,,,,,,,,,,,,,,,,,EFA1F375D76194FA51A3556A97E641E61685F914D446979DA50A551A4333FFD7}">
  <Meta udc="ABCDE.20150101.00001" fdc="NA" idc="NA" pip="NA" lot="G" lov="21,78,0" />
  <Skey ci="20170227">NbMR6W7u/9bukL5/6LLnGypU2O2CtUamqjVrQc92gP110CvDI+3vCwki+4GB5fl0N0z3YipYAR91hEo4CCqS3nHXhEQhV+UC9pH1Tq9TiUQHB+5uC6fI4EJgAS0ZCrAP2XqGYwhtHdM+ANkI5NdL6LFJZKwVhN8GMnLxfbphHFldtQJSJ94znR4vYepncPVerVdF4sNFW5s4sJ9xFfgQcD6UTM8OgadhHI7YnmEnB4FYwN628KSML4cmFBFux0Hs9wlmI5Hova1bXuvh12FDgIs0qTdAkT7a0O3y9XXJAfyi883WnIBJDAJg7haZhVfD4rqWzSOVxXx1o6iOtac66Q==</Skey>
  <Data type="X">Uofe+M5yhH+CRNteaFGFEZd4nnfDXxOfT3yiH9XdBulTJ74beiSFjAIRHS/sYKe/Ia/qFEtLj0tMSxQFkggYplk8Ju9BQQ+Mlq0aQKOejZI=</Data>
  <Hmac>3eP5wfunA5n0olDnZXNZYP4mmK4Nyq/+k54zUK2lboSeg6ku0kCj7KqUOnSaOCiM</Hmac>
  <Uses pi="y" pa="n" pfa="n" bio="n" otp="n" pin="n" />
</Auth>}

**Comment by hgehlot07** [comment]
`{<Auth uid="757759114195" tid="public" ts="2017-01-11T16:00:46" info="02{5985A44FE0C89A3A281A77B012527FFB384F08384073C34F21DF9399E108685E,EF58BD753FA309138ACD25466F23BFE08FE5B5E36EF7F77CBB3AEA12EC2609AF,,,20170111160046,,,,,,,,,,,,,,,,,,,,EFA1F375D76194FA51A3556A97E641E61685F914D446979DA50A551A4333FFD7}">
  <Meta udc="ABCDE.20150101.00001" fdc="NA" idc="NA" pip="NA" lot="G" lov="21,78,0" />
  <Skey ci="20170227">NbMR6W7u/9bukL5/6LLnGypU2O2CtUamqjVrQc92gP110CvDI+3vCwki+4GB5fl0N0z3YipYAR91hEo4CCqS3nHXhEQhV+UC9pH1Tq9TiUQHB+5uC6fI4EJgAS0ZCrAP2XqGYwhtHdM+ANkI5NdL6LFJZKwVhN8GMnLxfbphHFldtQJSJ94znR4vYepncPVerVdF4sNFW5s4sJ9xFfgQcD6UTM8OgadhHI7YnmEnB4FYwN628KSML4cmFBFux0Hs9wlmI5Hova1bXuvh12FDgIs0qTdAkT7a0O3y9XXJAfyi883WnIBJDAJg7haZhVfD4rqWzSOVxXx1o6iOtac66Q==</Skey>
  <Data type="X">Uofe+M5yhH+CRNteaFGFEZd4nnfDXxOfT3yiH9XdBulTJ74beiSFjAIRHS/sYKe/Ia/qFEtLj0tMSxQFkggYplk8Ju9BQQ+Mlq0aQKOejZI=</Data>
  <Hmac>3eP5wfunA5n0olDnZXNZYP4mmK4Nyq/+k54zUK2lboSeg6ku0kCj7KqUOnSaOCiM</Hmac>
  <Uses pi="y" pa="n" pfa="n" bio="n" otp="n" pin="n" />
</Auth>}`

**Comment by hgehlot07** [comment]
Skey ci="20170227" goinhg this way

**Comment by hgehlot07** [comment]
and value inside the tag is NbMR6W7u/9bukL5/6LLnGypU2O2CtUamqjVrQc92gP110CvDI+3vCwki+4GB5fl0N0z3YipYAR91hEo4CCqS3nHXhEQhV+UC9pH1Tq9TiUQHB+5uC6fI4EJgAS0ZCrAP2XqGYwhtHdM+ANkI5NdL6LFJZKwVhN8GMnLxfbphHFldtQJSJ94znR4vYepncPVerVdF4sNFW5s4sJ9xFfgQcD6UTM8OgadhHI7YnmEnB4FYwN628KSML4cmFBFux0Hs9wlmI5Hova1bXuvh12FDgIs0qTdAkT7a0O3y9XXJAfyi883WnIBJDAJg7haZhVfD4rqWzSOVxXx1o6iOtac66Q==

**Comment by ghost** [comment]
In case if your device need to send any extra information to the AUA, you may wrap the device XML in a device-AUA specific protocol and send it to AUA, AUA on the other side, may decode and get the final device XML. This is just an optional part, and the (Un)wrapFromAuaProtocol() needs to be implemented by you.

ALSO add one step to the troubleshooting steps:
5. Check if you are you using the correct API web address.

Remember, every parameter is different and secure in production environment: API web address, AUA/ASA license keys, encryption keys, digital signatures, Aadhaar numbers, etc.

If everything is working fine with the Staging and especially Pre-Production keys, then it should also work with Production keys, as the same code is running and generating the XML in same way. As this does not seem to point to a issue, we need to close it.

You may contact Aadhaar team for help in production environment.

**Comment by hgehlot07** [comment]
Hi Souvik

How to contact Aadhaar Technical team as the only tollfree number they have provided is not responding. Please send if you have any lead.

Thanking you
Himanshu Gehlot

**Comment by ghost** [comment]
Please find the group mentioned below, there you will get various email addresses of technical team.
[Aadhaar Authentication Discussions Group](https://groups.google.com/forum/#!forum/aadhaarauth)

Regards,
Souvik

**Comment by Mounika80244** [comment]
Hi @souvikdc9
