### ISSUE TITLE
error 937

### ISSUE THREAD

**Issue by porscheme** [souvikdc9/aadhaarapi.net#8]
I am getting 937 error with this code, any clue?

**Comment by ghost** [comment]
It's probably a technical error. Contact UIDAI team.

**Comment by porscheme** [comment]
Not sure if this ever worked?...
Below is the request and failure response I always got...

<Auth tid="public" ac="public" sa="ac" txn="20171206050007552" lk="MEaMX8fkRa6PqsqK6wGMrEXcXFl_oXHA-YuknI2uf0gKgZ80HaZgG3A" uid="999999990019" ver="1.6" rc="Y" xmlns="http://www.uidai.gov.in/authentication/uid-auth-request/1.0">
  <Uses pi="y" pa="y" pfa="n" bio="n" otp="n" pin="n" xmlns="" />
  <Meta udc="ABCDE.20150101.00001" fdc="NA" idc="NA" pip="NA" lot="G" lov="21,78,0" xmlns="" />
  <Skey ci="20200915" xmlns="">P3eDxn1HS7IkmT6biN/ARuVH4EA/g2kpk+ThZCekCVgkbEZbqzG04dYWDZWqqsZZbSFNQvg0aDIdryvdNMgmCjWu6R/Ji//ubgQbUNcjaJ8BLKckqhqmDntZlGxlmqOe+F6K1LbAY6N2/zzqnMUXw2+L3V468+SkU3wCBW5FRyzZ41hSwq04M87J5PIOPyUFPtEXOkSpMbGy2Q9cWgP1PZJG8dxOYdHj4VXGmrEr+NiVRsjNyznzJXhjFQ7pTSAnoK9HHEXPUURtb9CNKxQvojvE7qICgpwk3gmh+1UMXm8i6+xwc9aP9BjoJfphGQTYWNHRicrn/vQUZQgRczBVpA==</Skey>
  <Data type="X" xmlns="">m5UWnmLbxnFMBwsAm6P9kWqWrCS9kBl+eUmwIFWMF6XbZEQw5eU2jnr4sBfJjmNzrwalWZ1R1qZgT2ygOmNvZ9gTbnFxCfLXpEJ6l9YT+E7MNdwJwNSXWCa2G/IO3XRT3YQkH17aZSgHjVV5Yrzv7qDogzUlkOGWcUdpF/s9lC7vVb05Nuyn8T2kezd32jY+e3B+REObQEH3kKFH7hjp3/E7PG8styIvHjQ9GgwD89flWjQLhjDwngZH3dWfIfaxrrTikg5FkTjNm4KrKqFO/NRCsrIe+zDus7FocRFcMj5N88f0qwxGR5a/YREPcC7eK2voV+u8cNmYeC1Yx5fwP9ydbxwZXtdnS6eD9I7u9S1fMG64NLMt0vVK5oxqxH1Yx/sYy8WTCrlrvrqhxQDaAQkFvZG8f7QIHlnZHK6J3JGqrRebPC30Nff7Exb5OeOD</Data>
  <Hmac xmlns="">i1kxQw7+cEmOn/gugYU4g4tGwBMNSSH0GFhsjRZPiByPE9N7ec2oyo7VvZFwQZZA</Hmac>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>NhmR2xfBVsa+m1wcoJQmi9rWxXI=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>N3Xxa3UK9F6w6wKmzLWU3wNl15mYWNkGjAurJNJ4WKZhl3Yocwsg87O9zp7N0GS9UHR/DHSzRFpj9+l3sgrfnRKcwVIMF0B1xt1vwYz2mffQAKWyIaWOZdwFJa/QACXR1Snn1WDORMm1D9B9LJO8GAl8ZLxtuEpwCd8wJzGZKluN7uJSzuKwSHBKNBMxBuNTYEpXyofQRhzMobKdqIJjSr8c/GwS/0Etk0ZV1ulWxzXa1nwKjczODC3X/DSnKfvRp2R+I0OVSDuT2S86o9OWhWV7BRh0ab6pJqJ7e62W/mwRDRKrdzqxI9XgEMrVfbMe3RoUnSbWs1lnBoyUGrJXhA==</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509SubjectName>CN=Public AUA for Staging Services, OU=Staging Services, O=Public AUA, L=Bangalore, S=KA, C=IN</X509SubjectName>
        <X509Certificate>MIIDuDCCAqCgAwIBAgIGA7J+eqryMA0GCSqGSIb3DQEBBQUAMIGNMQswCQYDVQQGEwJJTjELMAkGA1UECBMCS0ExEjAQBgNVBAcTCUJhbmdhbG9yZTETMBEGA1UEChMKUHVibGljIEFVQTEZMBcGA1UECxMQU3RhZ2luZyBTZXJ2aWNlczEtMCsGA1UEAxMkUm9vdCBQdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMB4XDTE2MDUyNDE0NDAzMVoXDTIwMDUyNDE0NDAzMVowgYgxCzAJBgNVBAYTAklOMQswCQYDVQQIEwJLQTESMBAGA1UEBxMJQmFuZ2Fsb3JlMRMwEQYDVQQKEwpQdWJsaWMgQVVBMRkwFwYDVQQLExBTdGFnaW5nIFNlcnZpY2VzMSgwJgYDVQQDEx9QdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo4XxOsjK58Ud+tQd06Mk8Rd0qoyjA/3u+y0YVYEF6RgT8Ge1uVdTkIcVYaHyXuuHUPLLqGW1hPfVtn81UVIMGyrw5+t1c30wpGv3UJ6GCFu0sPGgG5NwkVbIUt2xgT/Or/kGzHjUJJy4Y6URSkZiDLDQQWRXvui5ZwwsYRJ8LhT0pSUwan1raG5Vl01GmlWVqsrCmnObuoYkN85iwG4/ERGshkgFCPak8B/jH3GPZSi1+FJLmCqMI1xxmTvf0kZb7ejm2IZFTo6ecYWJ1vylkzUI553RxVbnHCNZvFe3AyaKMyFlknFR0Fkl5+9Lpxz+VOajbCjicg7jIYCw76/xgQIDAQABoyEwHzAdBgNVHQ4EFgQUJHLir1/Tel8v/6OuIXpLS0JH8jIwDQYJKoZIhvcNAQEFBQADggEBAFE15qMGIlp8+M306FbhDEvo1vzxN2Pfvg/f92NXH59d2XZ/wuHxugL8qfcM5xkqsDeIRVxRdISpwiIWlqTitn6lenF85bvPQ09T/b09dVz/LxwU2Cm6+6H5/HZSoLtCKBOuRzAKQdxczpyfaqv9caFC+LegPQIm2HCwOM0A4KzhYcFhumGeyCbyVZsSQcJE7bYc/IHkR2erup7h5BACOZ/a+hHLPQok/uGvtEsR3roydNcNlR8Ja6Wc4eUf7kisTuZTxwRJI9DPVimbs0VAqhnsnVWAK3X4+6sFUq5WfHS4wTRhrR93JvEV5LlQ6UCXYOQMvTii8l07qxkDiysVsLQ=</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
</Auth>

<AuthRes ret="n" code="NA" txn="20171206050007552" err="937" info="02{49951232b1f45f281c7d4f70f3cbbc57c2afd9c0d6bb5f44578bf1304d4868d4,0000000000000000000000000000000000000000000000000000000000000000,0100000000000000,NA,NA,NA,NA,NA,1.6,20ef0f0c8d0eea98772412cea9b3b92612e3e53cb5e59152b5703165f56e8a53,efa1f375d76194fa51a3556a97e641e61685f914d446979da50a551a4333ffd7,ac,G,21|78|0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,efa1f375d76194fa51a3556a97e641e61685f914d446979da50a551a4333ffd7}" ts="2017-12-07T06:30:39.988+05:30" />

**Comment by porscheme** [comment]
Not sure if this ever worked!. Below is the request and failed response

<Auth tid="public" ac="public" sa="ac" txn="20171206050007552" lk="MEaMX8fkRa6PqsqK6wGMrEXcXFl_oXHA-YuknI2uf0gKgZ80HaZgG3A" uid="999999990019" ver="1.6" rc="Y" xmlns="http://www.uidai.gov.in/authentication/uid-auth-request/1.0">
  <Uses pi="y" pa="y" pfa="n" bio="n" otp="n" pin="n" xmlns="" />
  <Meta udc="ABCDE.20150101.00001" fdc="NA" idc="NA" pip="NA" lot="G" lov="21,78,0" xmlns="" />
  <Skey ci="20200915" xmlns="">P3eDxn1HS7IkmT6biN/ARuVH4EA/g2kpk+ThZCekCVgkbEZbqzG04dYWDZWqqsZZbSFNQvg0aDIdryvdNMgmCjWu6R/Ji//ubgQbUNcjaJ8BLKckqhqmDntZlGxlmqOe+F6K1LbAY6N2/zzqnMUXw2+L3V468+SkU3wCBW5FRyzZ41hSwq04M87J5PIOPyUFPtEXOkSpMbGy2Q9cWgP1PZJG8dxOYdHj4VXGmrEr+NiVRsjNyznzJXhjFQ7pTSAnoK9HHEXPUURtb9CNKxQvojvE7qICgpwk3gmh+1UMXm8i6+xwc9aP9BjoJfphGQTYWNHRicrn/vQUZQgRczBVpA==</Skey>
  <Data type="X" xmlns="">m5UWnmLbxnFMBwsAm6P9kWqWrCS9kBl+eUmwIFWMF6XbZEQw5eU2jnr4sBfJjmNzrwalWZ1R1qZgT2ygOmNvZ9gTbnFxCfLXpEJ6l9YT+E7MNdwJwNSXWCa2G/IO3XRT3YQkH17aZSgHjVV5Yrzv7qDogzUlkOGWcUdpF/s9lC7vVb05Nuyn8T2kezd32jY+e3B+REObQEH3kKFH7hjp3/E7PG8styIvHjQ9GgwD89flWjQLhjDwngZH3dWfIfaxrrTikg5FkTjNm4KrKqFO/NRCsrIe+zDus7FocRFcMj5N88f0qwxGR5a/YREPcC7eK2voV+u8cNmYeC1Yx5fwP9ydbxwZXtdnS6eD9I7u9S1fMG64NLMt0vVK5oxqxH1Yx/sYy8WTCrlrvrqhxQDaAQkFvZG8f7QIHlnZHK6J3JGqrRebPC30Nff7Exb5OeOD</Data>
  <Hmac xmlns="">i1kxQw7+cEmOn/gugYU4g4tGwBMNSSH0GFhsjRZPiByPE9N7ec2oyo7VvZFwQZZA</Hmac>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>NhmR2xfBVsa+m1wcoJQmi9rWxXI=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>N3Xxa3UK9F6w6wKmzLWU3wNl15mYWNkGjAurJNJ4WKZhl3Yocwsg87O9zp7N0GS9UHR/DHSzRFpj9+l3sgrfnRKcwVIMF0B1xt1vwYz2mffQAKWyIaWOZdwFJa/QACXR1Snn1WDORMm1D9B9LJO8GAl8ZLxtuEpwCd8wJzGZKluN7uJSzuKwSHBKNBMxBuNTYEpXyofQRhzMobKdqIJjSr8c/GwS/0Etk0ZV1ulWxzXa1nwKjczODC3X/DSnKfvRp2R+I0OVSDuT2S86o9OWhWV7BRh0ab6pJqJ7e62W/mwRDRKrdzqxI9XgEMrVfbMe3RoUnSbWs1lnBoyUGrJXhA==</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509SubjectName>CN=Public AUA for Staging Services, OU=Staging Services, O=Public AUA, L=Bangalore, S=KA, C=IN</X509SubjectName>
        <X509Certificate>MIIDuDCCAqCgAwIBAgIGA7J+eqryMA0GCSqGSIb3DQEBBQUAMIGNMQswCQYDVQQGEwJJTjELMAkGA1UECBMCS0ExEjAQBgNVBAcTCUJhbmdhbG9yZTETMBEGA1UEChMKUHVibGljIEFVQTEZMBcGA1UECxMQU3RhZ2luZyBTZXJ2aWNlczEtMCsGA1UEAxMkUm9vdCBQdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMB4XDTE2MDUyNDE0NDAzMVoXDTIwMDUyNDE0NDAzMVowgYgxCzAJBgNVBAYTAklOMQswCQYDVQQIEwJLQTESMBAGA1UEBxMJQmFuZ2Fsb3JlMRMwEQYDVQQKEwpQdWJsaWMgQVVBMRkwFwYDVQQLExBTdGFnaW5nIFNlcnZpY2VzMSgwJgYDVQQDEx9QdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo4XxOsjK58Ud+tQd06Mk8Rd0qoyjA/3u+y0YVYEF6RgT8Ge1uVdTkIcVYaHyXuuHUPLLqGW1hPfVtn81UVIMGyrw5+t1c30wpGv3UJ6GCFu0sPGgG5NwkVbIUt2xgT/Or/kGzHjUJJy4Y6URSkZiDLDQQWRXvui5ZwwsYRJ8LhT0pSUwan1raG5Vl01GmlWVqsrCmnObuoYkN85iwG4/ERGshkgFCPak8B/jH3GPZSi1+FJLmCqMI1xxmTvf0kZb7ejm2IZFTo6ecYWJ1vylkzUI553RxVbnHCNZvFe3AyaKMyFlknFR0Fkl5+9Lpxz+VOajbCjicg7jIYCw76/xgQIDAQABoyEwHzAdBgNVHQ4EFgQUJHLir1/Tel8v/6OuIXpLS0JH8jIwDQYJKoZIhvcNAQEFBQADggEBAFE15qMGIlp8+M306FbhDEvo1vzxN2Pfvg/f92NXH59d2XZ/wuHxugL8qfcM5xkqsDeIRVxRdISpwiIWlqTitn6lenF85bvPQ09T/b09dVz/LxwU2Cm6+6H5/HZSoLtCKBOuRzAKQdxczpyfaqv9caFC+LegPQIm2HCwOM0A4KzhYcFhumGeyCbyVZsSQcJE7bYc/IHkR2erup7h5BACOZ/a+hHLPQok/uGvtEsR3roydNcNlR8Ja6Wc4eUf7kisTuZTxwRJI9DPVimbs0VAqhnsnVWAK3X4+6sFUq5WfHS4wTRhrR93JvEV5LlQ6UCXYOQMvTii8l07qxkDiysVsLQ=</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
</Auth>

<AuthRes ret="n" code="NA" txn="20171206050007552" err="937" info="02{49951232b1f45f281c7d4f70f3cbbc57c2afd9c0d6bb5f44578bf1304d4868d4,0000000000000000000000000000000000000000000000000000000000000000,0100000000000000,NA,NA,NA,NA,NA,1.6,20ef0f0c8d0eea98772412cea9b3b92612e3e53cb5e59152b5703165f56e8a53,efa1f375d76194fa51a3556a97e641e61685f914d446979da50a551a4333ffd7,ac,G,21|78|0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,efa1f375d76194fa51a3556a97e641e61685f914d446979da50a551a4333ffd7}" ts="2017-12-07T06:30:39.988+05:30" />

**Comment by porscheme** [comment]
Not sure if this ever worked!. Attached is the request and failed response.


[AuthReq.zip](https://github.com/souvikdc9/aadhaarapi.net/files/1537427/AuthReq.zip)

**Comment by porscheme** [comment]
Is the license key and cert valid?

**Comment by ghost** [comment]
Yes, it really worked, which you can estimate from the number of stars and NuGet download stats. This problem may be temporary. Make sure the license key and cert is latest from the UIDAI developer website.

**Comment by porscheme** [comment]
Have been able verify last two days? Are you saying key and cert attached with the source not latest? If so, from where do I download the license key and cert?

**Comment by porscheme** [comment]
How do I contact UIDAI team?

**Comment by ghost** [comment]
Developer Website: https://authportal.uidai.gov.in/developer
Discussion Group: https://groups.google.com/forum/#!forum/aadhaarauth
Email: community.tc@uidai.net.in
